name: desi-cmb-fli
channels:
  - conda-forge
dependencies:
  - python=3.11
  - mpi4py
  - mpi4jax>=0.3.15
  - ipykernel
  - numpy
  - scipy
  - pandas>=2.1
  - fitsio
  - pyyaml
  - matplotlib
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - pre-commit
  - mkdocs
  - mkdocs-material
  - pymdown-extensions
  - pip
  - pip:
    - numpyro>=0.13
    - jaxpm==0.0.2
    - "jax-cosmo @ git+https://github.com/DifferentiableUniverseInitiative/jax_cosmo@master"
    - corner>=2.1.0
